language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2" 
before_install:
  - npm update -g npm
before_script:
  - npm install -g grunt-cli

branches:
  only:
    - master
    - development
