
var fs = require("fs");
var oldLoader = require.extensions['.js'];

module.exports = function(sourceDir){

    //find current scripts
    require.extensions['.js'] = function(module, filename) {
        if (filename.indexOf("sourceDir") > -1){
           var content = fs.readFileSync(filename, 'utf8');
          // Parse the file content and give to module.exports
          var covintro = "/* automatically generated by JSCoverage - do not edit */";
            covintro += " if (typeof _$jscoverage === 'undefined'){ _$jscoverage = {};}";
            covintro += " if (! _$jscoverage['source.js']) {";
            covintro += " _$jscoverage['source.js'] = [];";
            covintro += " _$jscoverage['source.js'][1] = 0;";
            covintro += " _$jscoverage['source.js'][2] = 0;";
            covintro += " _$jscoverage['source.js'][1]++;";
            covintro += " console.log(_$jscoverage['source.js']);";
            covintro += "} ";
            //not the actual source, just for simplicity sake
            covintro += " _$jscoverage['source.js'].source = [\"source line1\",\"source line2\"];";
            
            content = covintro + content;
            module.exports = eval(content);
        }else{
            oldLoader(module,filename);
        }
    };
};